### ISSUE TITLE
column autocompletion?

### ISSUE THREAD

**Issue by daranzolin** [moodymudskipper/nakedpipe#10]
I am still a convert to nakedpipe, but the *one* disadvantage I've experienced is the absence of column autocompletion within various tidyverse functions. For example, I get this from the pipe:

<img width="266" alt="col-autocomplete" src="https://user-images.githubusercontent.com/9537384/77597380-ecdbf800-6ebb-11ea-9d69-2a1117afc8ed.png">

But nothing from nakedpipe:

<img width="251" alt="noautocomplete" src="https://user-images.githubusercontent.com/9537384/77597437-1dbc2d00-6ebc-11ea-8cbd-28f3e9136b0f.png">

[As I tweeted,](https://twitter.com/daranzolin/status/1242598503823503361?s=20) I'm still loving the coding experience and will continue using it. But the autocompletion would be amazing. Admittedly, I have no idea how it works behind the scenes.

**Comment by moodymudskipper** [comment]
RStudio have implemented an adhoc behavior for magrittr's pipe, I'm not sure if I can leverage it for the naked pipe, it's probably hardcoded and I don't see them supporting the nakedpipe even when it's on CRAN :). I ll leave this open just in case but don't hold your breath! 
The thing that annoys me personally is that I get warning icons in the margin for wrong number of arguments, which you don't get with magrittr.

**Comment by moodymudskipper** [comment]
BTW thanks so much for the exposure on twitter, this really helps

**Comment by daranzolin** [comment]
Do you think it's worth filing an issue on the RStudio repo? There are numerous issues related to autocompletion.

**Comment by moodymudskipper** [comment]
Maybe but probably better once the package is on CRAN, for now I don't think it'll be taken seriously.
Also I'm not sure what behavior I expect in a more general situation than the example you gave, so I'd need to define those expectations, I'm spending a few days without computer now, writing all this from my phone, I'll take a look when I'm back to geeking.

**Comment by moodymudskipper** [comment]
closing for now to unclutter the issues as I have no leverage on this
