### ISSUE TITLE
right arrow assignment after ~~

### ISSUE THREAD

**Issue by daranzolin** [moodymudskipper/nakedpipe#13]
It looks like right arrow assignment doesn't work after `~~`. The first example using left arrow assignment works, but not the second. Reprex below:

``` r
library(nakedpipe)
suppressPackageStartupMessages(library(dplyr))
iris %.% {
  filter(Sepal.Length > 5)
  ~~ species_count <- count(., Species)
} -> iris_subset

iris %.% {
  filter(Sepal.Length > 5)
  ~~ count(., Species) -> species_count
} -> iris_subset
#> Error in eval_step(x, y, pf): Wrong syntax! If you mean to assign as a side effect you shoulduse a `~~` prefix
```

<sup>Created on 2020-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by daranzolin** [comment]
Interestingly though, it works with the `%->%` operator from zeallot:

``` r
library(zeallot)
library(nakedpipe)
suppressPackageStartupMessages(library(dplyr))
iris %.% {
  filter(Sepal.Length > 5)
  ~~ count(., Species) %->% species_count
} -> iris_subset
species_count
#> # A tibble: 3 x 2
#>   Species        n
#>   <fct>      <int>
#> 1 setosa        22
#> 2 versicolor    47
#> 3 virginica     49
```

<sup>Created on 2020-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by moodymudskipper** [comment]
It's because `~` has lower precedence than `%->%` but higher than `<-` so `<-` needs adhoc magic. Seems I forgot to support `->` when implementing this magic but I believe it's an easy fix. Thanks for reporting!

**Comment by moodymudskipper** [comment]
now fixed!
