### ISSUE TITLE
%P.% operator to print each step to the console?

### ISSUE THREAD

**Issue by daranzolin** [moodymudskipper/nakedpipe#14]
As the creator of ViewPipeSteps, I know there's interest for seeing the output of each step in a chain. What do you think about an operator that prints each step to the console? Maybe `%P.%`?

**Comment by moodymudskipper** [comment]
I have considered it, and have not dismissed it.
I think my concern was that if this family grows we need to put more thought into what goes in or doesn't, we could also use `View()` on every step, or print the `summary()`, or the `str()`. Another that I would really like is to have a `%C.%` pipe to compare each output with the previous one. Some comparison functions exist but none is as flexible as I need so I'd need to build it myself I think (tidylog works only with tidy verbs, all.equal is not quite enough, arsenal::compare has interesting features but doesn't fit right in). 

I'll add `%P. %` though it as it's the one that makes the most sense I guess!

**Comment by daranzolin** [comment]
Maybe put all the display/inspect/view options in a separate, complimentary package called {exhibitionist}?

**Comment by moodymudskipper** [comment]
it's done :), along with a `%V.%` pipe and assigning counterparts :)
