### ISSUE TITLE
temporary variable assignment restricted to nakedpipe scope?

### ISSUE THREAD

**Issue by daranzolin** [moodymudskipper/nakedpipe#17]
Just thinking out loud, but I was experimenting with some alternative nested data patterns and thought it might be useful to be able to assign temporary variables restricted to the nakedpipe scope. For example, I wouldn't want `cyl_data` to enter my global environment here:

```
library(nakedpipe)
library(tibble)

mtcars %.% {
  split(.$cyl)
  ~~ . -> cyl_data
  lapply(., function(df) lm(mpg ~ wt, data = df))
  tibble(
    cyl = c(4, 6, 8),
    data = cyl_data, 
    model = .)
}
```

This might be too fringey and weird, but I would possibly write code like this in the future.

**Comment by moodymudskipper** [comment]
Hi David, do you have a syntax in mind? I wanted a way to save intermediate results conveniently so I don't think I want to change this behavior. I see how what you want is useful though. 

What about : 

    ~~ . -> (cyl_data) 

For your desired behavior? Does it appear intuitive enough?

**Comment by daranzolin** [comment]
I like `~~ . -> (cyl_data)` a lot!

And yes, I agree, I wouldn't want to change the original behavior, as sometimes it is also useful to assign intermediary results to the global env. Sorry I wasn't more clear.

**Comment by moodymudskipper** [comment]
assignment to temp variables is documented and works with `%D.%`, it fails explicitly when trying to convert, because *magrittr*'s environments don't permit it.
