### ISSUE TITLE
addin to translate nakedpipe to 'regular' magrittr?

### ISSUE THREAD

**Issue by daranzolin** [moodymudskipper/nakedpipe#9]
I spent the day with nakedpipe and really enjoyed it! However, I work in an office with relative newcomers to R and this is probably a tad exotic for them. But having an RStudio add-in that 'translates' nakedpipe code to 'regular' magrittr code would let me enjoy nakedpipe while not stifling collaboration.

**Comment by moodymudskipper** [comment]
Thanks for giving it a chance!
I like your suggestion. I think I can do it with string manipulation only, no need to parse the call. 
The addin would work on all pipe variants, we d just lose the debugging or logging feature after convertion. 
I can either deal with side effects by using `%T>%`,  on `{} `expressions, which won't be 100% robust (e.g. Assignments). Or remove side effects altogether when converting. Or fail with message saying side effects are not supported for conversion to magrittr (easiest and safest).

**Comment by daranzolin** [comment]
Not my call I guess, but I think failing with the message that side effects are not supported makes the most sense (and is happily the easiest and safest).

**Comment by moodymudskipper** [comment]
We could have recursive pipe calls.
Just check if any nakedpipe symbol exists in the `{}` expression and fail if we find one.
User can still convert in several steps from the inside out in those rare cases.

**Comment by moodymudskipper** [comment]
I finally used a single addin for both conversions.

Here's the result :  

![nakedpipe_addin](https://user-images.githubusercontent.com/18351714/84393270-add85b80-abfb-11ea-8a7d-3ec4c8c59d55.gif)

**Comment by daranzolin** [comment]
I used the new addin with a designated hot key and it works seamlessly. Fantastic tool. The indentation is a little different than my personal tastes, but I will be using this as of today. I may even demo it in an Rmd template review meeting tomorrow. Thanks for making it happen!

As for CRAN readiness, I don't have an informed opinion (my previous few submissions were rejected for various reasons lol), but this feels like a pretty robust package already.

**Comment by moodymudskipper** [comment]
The addin is documented and works with all current features except for side effect assignments, which I think cannot work with magrittr unless I build a very weird translations. So I think I can close this
